### PR TITLE
fix: greatly simplify rusb usage

### PR DESCRIPTION
**Pull request by prestwich**

### CODE REVIEW

**Review by DaniPopes — APPROVED** [review]
LGTM

**Comment by prestwich** [comment]
leaving this open so that @naps62 and @xJonathanLEI can check it before merge 👍

**Comment by naps62** [comment]
Allright. this seems to fix both issues for me, although it still has one less serious wrinkle.

```rust
#[tokio::main]
async fn main() {
    // first call, works
    let _ = dbg!(call_ledger().await);

    // tokio::time::sleep(tokio::time::Duration::from_millis(10)).await;

    // second call, if done without sleep first, fails with `hid_error is not implemented yet`
    let _ = dbg!(call_ledger().await);
}
```

including the sleep makes this work consistently.
without the sleep, the 2nd call will fail ~80% of the time:

```
[src/main.rs:11] call_ledger().await = Ok(
    LedgerEthereum {
        transport: Mutex {
            is_locked: false,
            has_waiters: false,
        },
        derivation: Other(
            "m/44'/60'/0'/0/0",
        ),
        chain_id: 1,
        address: ...........,
    },
)
[src/main.rs:12] call_ledger().await = Err(
    LedgerError(
        NativeTransportError(
            CantOpen(
                HidApiError {
                    message: "hid_error is not implemented yet",
                },
            ),
        ),
    ),
)
```

**Comment by xJonathanLEI** [comment]
Will check whether this works on Android tomorrow and revert.

**Comment by prestwich** [comment]
> nevermind. there's still a panic if I try to instantiate a ledger twice while the device is locked (1st call fails with Err(UnexpectedNullResponse). Second call panics at hid.rs:143

Are you sure the line number is correct? that line is currently `first_ledger(api).map(Self::from_device)` which should not be capable of panicking

> Other than that, there's still a less serious wrinkle. the code below, without the sleep, fails 80% of the time on the second call (Err, not panic). adding the sleep makes it work more consistently.

This sounds like it might be a race condition between instnatiating the new task and releasing the resource in the old task? I'll play around with it

**Comment by naps62** [comment]
not sure what I was on about with the panic thing. seems gone now, can't reproduce even pointing to the same `rev`. I'll assume it was still the sleep deprivation

2nd issue (two successive calls without waiting) still exists, although I can work with it already, if you feel you need to merge this and research that one later

thanks very much for the support btw :pray:

**Comment by xJonathanLEI** [comment]
Just tested  9f86de4edf71b4c631f870ed95548362e196ead7 on Android and it works perfectly. So far no issue found.

**Comment by xJonathanLEI** [comment]
Actually, no. I made a mistake and tested the wrong code. It actually no longer compiles on Android. I will look into it.

**Comment by xJonathanLEI** [comment]
Just sent #130 to fix the compilation error. It's trivial.

**Comment by xJonathanLEI** [comment]
Yeah I tried multiple times. In fact, I've never encountered this error even once before this PR.

**Comment by prestwich** [comment]
is there an easy way for me to replicate your test environment without buying an android device @xJonathanLEI? Would be nice to check things locally 😅

**Comment by naps62** [comment]
I have an android, and am willing to do some debugging to narrow it down
If you have a way to replicate I can give it a try

**Comment by naps62** [comment]
> Are you able to reproduce the same bug? I can make a temp repo/gist for this if that's helpful. To make it easier I will use coins-ledger directly for the repro.

I saw this bug a few times, but seems mostly at random, and never frequently enough to debug.
if it's as you say and it happens consistently on android, I'd be happy to try your repo

I guess there's a lot of variance depending on hardware in all this (so far I tested only on Linux)

**Comment by xJonathanLEI** [comment]
Working on the reproducer and noticed that like dumping addresses, signing messages also works perfectly.

**Comment by xJonathanLEI** [comment]
@naps62 The reproducer is now available: [xJonathanLEI/coins-android-bug-repro](https://github.com/xJonathanLEI/coins-android-bug-repro).

@prestwich Turns out the error occurs when calling `transport.exchange()`, returning a `ResponseTooShort([])` error. So it's _not_ the case that the device returns an empty successful message as we thought before.

Again note that this issue only occurs when signing a transaction but not a message. I originally coded the reproducer to sign a "hellow world" message but it ended up succeeding both on `main` and on this PR lol.

**Comment by prestwich** [comment]
Alright, so i can repro without android. Will be diving into this today 🎉

**Comment by prestwich** [comment]
okay I tracked this down to an off-by-one in the write buffer that was sending the device incorrect data. I am still unsure why this was significant only for certain instructions, but it seems to be fixed in the latest commit. Would you mind verifying on android for me? :D

**Comment by xJonathanLEI** [comment]
Tested dumping addresses and signing a "hello world" message - both work perfectly. All good on my side now. Thanks!

**Comment by prestwich** [comment]
thanks y'all! I've just published at 0.9.2 and yanked 0.9.1 and 0.9.0 🎉

**Comment by prestwich** [comment]
I'll address the race condition in 0.9.3 👍

**Pull request merged**
